/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as MetadataRouteImport } from './routes/metadata'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RunningRouteImport } from './routes/running'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as SelectRouteImport } from './routes/select'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const MetadataRoute = MetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningRoute = RunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/metadata': typeof MetadataRoute
  '/results': typeof ResultsRoute
  '/running': typeof RunningRoute
  '/runtime': typeof RuntimeRoute
  '/select': typeof SelectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/metadata': typeof MetadataRoute
  '/results': typeof ResultsRoute
  '/running': typeof RunningRoute
  '/runtime': typeof RuntimeRoute
  '/select': typeof SelectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/metadata': typeof MetadataRoute
  '/results': typeof ResultsRoute
  '/running': typeof RunningRoute
  '/runtime': typeof RuntimeRoute
  '/select': typeof SelectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dataset'
    | '/metadata'
    | '/results'
    | '/running'
    | '/runtime'
    | '/select'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dataset'
    | '/metadata'
    | '/results'
    | '/running'
    | '/runtime'
    | '/select'
  id:
    | '__root__'
    | '/'
    | '/dataset'
    | '/metadata'
    | '/results'
    | '/running'
    | '/runtime'
    | '/select'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetRoute: typeof DatasetRoute
  MetadataRoute: typeof MetadataRoute
  ResultsRoute: typeof ResultsRoute
  RunningRoute: typeof RunningRoute
  RuntimeRoute: typeof RuntimeRoute
  SelectRoute: typeof SelectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metadata': {
      id: '/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof MetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running': {
      id: '/running'
      path: '/running'
      fullPath: '/running'
      preLoaderRoute: typeof RunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetRoute: DatasetRoute,
  MetadataRoute: MetadataRoute,
  ResultsRoute: ResultsRoute,
  RunningRoute: RunningRoute,
  RuntimeRoute: RuntimeRoute,
  SelectRoute: SelectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
